host: my.cmems-du.eu
source: Core/INSITU_GLO_TS_REP_OBSERVATIONS_013_001_b/CORIOLIS-GLOBAL-EasyCORA-OBS/
target: test
exclude:
  - arctic
  - baltic
  - global
  - mediterrane # [sic]
  - northwestshelf
  - southwestshelf
